# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1202, 834)
        Form.setStyleSheet("#Form{\n"
"background-color:#F1FEFF;\n"
"}\n"
"QPushButton{\n"
"background-color:white;\n"
"border:none;\n"
"}\n"
"#btn_delete_nomina,#btn_search_nomina,#btn_add_nomina,#btn_edit_nomina {\n"
"background-color:#7ECECF;\n"
"font-family:Noto Serif Sinhala ExtraBold;\n"
"color:#fff;\n"
"font-size:14px;\n"
"height:50px;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"#btn_delete_nomina:hover,#btn_search_nomina:hover,#btn_add_nomina:hover,#btn_edit_nomina:hover {\n"
"background-color:black}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(parent=Form)
        self.tableView.setMinimumSize(QtCore.QSize(500, 0))
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(59, 5, 59, -1)
        self.verticalLayout.setSpacing(28)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add_nomina = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_nomina.setFont(font)
        self.btn_add_nomina.setObjectName("btn_add_nomina")
        self.verticalLayout.addWidget(self.btn_add_nomina)
        self.btn_delete_nomina = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete_nomina.setFont(font)
        self.btn_delete_nomina.setObjectName("btn_delete_nomina")
        self.verticalLayout.addWidget(self.btn_delete_nomina)
        self.btn_edit_nomina = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_edit_nomina.setFont(font)
        self.btn_edit_nomina.setStyleSheet("")
        self.btn_edit_nomina.setObjectName("btn_edit_nomina")
        self.verticalLayout.addWidget(self.btn_edit_nomina)
        self.btn_search_nomina = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search_nomina.setFont(font)
        self.btn_search_nomina.setStyleSheet("")
        self.btn_search_nomina.setObjectName("btn_search_nomina")
        self.verticalLayout.addWidget(self.btn_search_nomina)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(10, 10))
        self.label.setMaximumSize(QtCore.QSize(800, 800))
        self.label.setStyleSheet("heigth:8px")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("userOnDesktop.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 75)
        self.horizontalLayout.setStretch(1, 25)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_add_nomina.setText(_translate("Form", "Agregar nueva nomina"))
        self.btn_delete_nomina.setText(_translate("Form", "Eliminar nomina"))
        self.btn_edit_nomina.setText(_translate("Form", "Editar nomina"))
        self.btn_search_nomina.setText(_translate("Form", "Busqueda de nominas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
