# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/create_nominas_quincena.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1051, 694)
        Form.setStyleSheet("#tableView{\n"
"border:1px solid #000;\n"
"}\n"
"QFrame{\n"
"border:none;\n"
"}\n"
"\n"
"#title_box{\n"
"background-color:#fff;\n"
"border:1px solid #000;\n"
"min-height:52px;\n"
"}\n"
"\n"
"#Form{\n"
"background-color:#E0EDEE;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:white;\n"
"border:none;\n"
"}\n"
"#confirm, #prev_pdf, #prev_create,#filter,#listado_nominas{\n"
"background-color:#fff;\n"
"color:#000;\n"
"font-size:14px;\n"
"border-radius:2px;\n"
"width:100%;\n"
"height:52px;\n"
"border:1px solid #000;\n"
"}\n"
"\n"
"#confirm:hover, #prev_pdf:hover, #prev_create:hover,#filter:hover, #listado_nominas:hover{\n"
"background-color:#efe;\n"
"color:#000;\n"
"font-size:14px;\n"
"border-radius:2px;\n"
"width:100%;\n"
"height:52px;\n"
"border:1px solid #000;\n"
"}")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(30, 25, 25, 25)
        self.horizontalLayout_4.setSpacing(25)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_box = QtWidgets.QWidget(self.frame)
        self.title_box.setObjectName("title_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.title_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.title_box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.title_box)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(9, -1, -1, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setStyleSheet("")
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.prev_create = QtWidgets.QPushButton(self.frame_3)
        self.prev_create.setObjectName("prev_create")
        self.verticalLayout.addWidget(self.prev_create)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.prev_pdf = QtWidgets.QPushButton(self.frame_3)
        self.prev_pdf.setObjectName("prev_pdf")
        self.verticalLayout.addWidget(self.prev_pdf)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.listado_nominas = QtWidgets.QPushButton(self.frame_3)
        self.listado_nominas.setObjectName("listado_nominas")
        self.verticalLayout.addWidget(self.listado_nominas)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.confirm = QtWidgets.QPushButton(self.frame_3)
        self.confirm.setObjectName("confirm")
        self.verticalLayout.addWidget(self.confirm)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.horizontalLayout_4.setStretch(0, 75)
        self.horizontalLayout_4.setStretch(1, 25)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Crear Nominas - Semanal"))
        self.prev_create.setText(_translate("Form", "Crear Modelo de Nomina"))
        self.prev_pdf.setText(_translate("Form", "Recibo de Nominas PDF"))
        self.listado_nominas.setText(_translate("Form", "Listado Nominas PDF"))
        self.confirm.setText(_translate("Form", "Confirmar Nomina"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
