# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/historial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(727, 575)
        Form.setStyleSheet("#Form{\n"
"background-color:#fff;\n"
"}\n"
"QFrame{\n"
"border:none;\n"
"}\n"
"\n"
"#btn_search{\n"
"padding:15px;\n"
"border: 2px solid #222;\n"
"border-radius:4px;\n"
"background-color: rgb(202, 255, 249);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Lao SemCond")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setStyleSheet("border: 2px solid #222")
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_search = QtWidgets.QComboBox(self.frame_3)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_search.setAutoFillBackground(False)
        self.btn_search.setStyleSheet("QComboBox {\n"
"    qproperty-alignment: \'AlignCenter\'; /* Centrar texto visible */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    text-align: center; /* Centrar texto en opciones desplegables */\n"
"}\n"
"")
        self.btn_search.setEditable(False)
        self.btn_search.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.btn_search.setPlaceholderText("")
        self.btn_search.setDuplicatesEnabled(False)
        self.btn_search.setFrame(True)
        self.btn_search.setObjectName("btn_search")
        self.btn_search.addItem("")
        self.btn_search.setItemText(0, "Busqueda de Acciones")
        self.btn_search.addItem("")
        self.btn_search.addItem("")
        self.btn_search.addItem("")
        self.btn_search.addItem("")
        self.btn_search.addItem("")
        self.verticalLayout.addWidget(self.btn_search)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Historial de Acciones"))
        self.btn_search.setCurrentText(_translate("Form", "Busqueda de Acciones"))
        self.btn_search.setItemText(1, _translate("Form", "Alfabeticamente A-Z"))
        self.btn_search.setItemText(2, _translate("Form", "Alfabeticamente Z-A"))
        self.btn_search.setItemText(3, _translate("Form", "Cedula (mayor a menor)"))
        self.btn_search.setItemText(4, _translate("Form", "Cedula (menor a mayor)"))
        self.btn_search.setItemText(5, _translate("Form", "Por Nombre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
