# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys 
import os
if getattr(sys, 'frozen', False):  
    resources_path = sys._MEIPASS  # Carpeta temporal donde PyInstaller extrae los archivos
else:
    resources_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1271, 651)
        Form.setStyleSheet("#personal_tab.active {\n"
"    background-color: #54BCBD;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"}\n"
"#Form{\n"
"background-color:#F1FEFF;\n"
"}\n"
"QPushButton{\n"
"background-color:white;\n"
"border:none;\n"
"}\n"
"#btn_delete_nomina, #delete_power, #add_power,#btn_search_nomina,#btn_add_nomina,#btn_edit_nomina, #eliminar_empleado_gestion, #crear_empleado_gestion, #editar_empleado_gestion {\n"
"background-color:#7ECECF;\n"
"font-family:Noto Serif Sinhala ExtraBold;\n"
"color:#fff;\n"
"font-size:14px;\n"
"border-radius:2px;\n"
"width:100%;\n"
"height:32px;\n"
"}\n"
"\n"
"#btn_delete_nomina:hover,#btn_search_nomina:hover,#btn_add_nomina:hover,#btn_edit_nomina:hover,#delete_power:hover, #add_power:hover, #eliminar_empleado_gestion:hover, #crear_empleado_gestion:hover, #editar_empleado_gestion:hover {\n"
"background-color:#000;}\n"
"\n"
"#nomina_mensual_tab,#all_nominas, #nomina_quincenal_tab, #personal_tab,#cestatickets_tab,#nomina_semanal_tab {\n"
"min-width:130px;\n"
"min-height:40px;\n"
"padding:0 20px;\n"
"border-radius: 4px;\n"
"border: 1px solid #000;\n"
"}\n"
"#nomina_mensual_tab:hover, #nomina_semanal_tab:hover, #nomina_quincenal_tab:hover, #personal_tab:hover, #all_nominas:hover,#cestatickets_tab:hover{\n"
"min-width:130px;\n"
"min-height:40px;\n"
"background-color: #54BCBD;\n"
"color:#fff;\n"
"padding:0 20px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton::before, QPushButton::after{\n"
"content:\'33333333\';\n"
"color:red}\n"
"\n"
"#horizontalLayout_2{\n"
"display:none;\n"
"background-color:#000;\n"
"}\n"
"QComboBox {\n"
"    text-align: center; /* Centra el texto en el área visible */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    text-align: center; /* Centra el texto en las opciones desplegables */\n"
"}\n"
"")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 15, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.personal_tab = QtWidgets.QPushButton(Form)
        self.personal_tab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.personal_tab.setObjectName("personal_tab")
        self.horizontalLayout_2.addWidget(self.personal_tab)
        self.nomina_semanal_tab = QtWidgets.QPushButton(Form)
        self.nomina_semanal_tab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nomina_semanal_tab.setStyleSheet("")
        self.nomina_semanal_tab.setObjectName("nomina_semanal_tab")
        self.horizontalLayout_2.addWidget(self.nomina_semanal_tab)
        self.nomina_quincenal_tab = QtWidgets.QPushButton(Form)
        self.nomina_quincenal_tab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nomina_quincenal_tab.setStyleSheet("")
        self.nomina_quincenal_tab.setObjectName("nomina_quincenal_tab")
        self.horizontalLayout_2.addWidget(self.nomina_quincenal_tab)
        self.nomina_mensual_tab = QtWidgets.QPushButton(Form)
        self.nomina_mensual_tab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nomina_mensual_tab.setObjectName("nomina_mensual_tab")
        self.horizontalLayout_2.addWidget(self.nomina_mensual_tab)
        self.cestatickets_tab = QtWidgets.QPushButton(Form)
        self.cestatickets_tab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cestatickets_tab.setObjectName("cestatickets_tab")
        self.horizontalLayout_2.addWidget(self.cestatickets_tab)
        self.all_nominas = QtWidgets.QPushButton(Form)
        self.all_nominas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.all_nominas.setObjectName("all_nominas")
        self.horizontalLayout_2.addWidget(self.all_nominas)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tiempo = QtWidgets.QLabel(Form)
        self.tiempo.setMinimumSize(QtCore.QSize(60, 50))
        self.tiempo.setMaximumSize(QtCore.QSize(50, 50))
        self.tiempo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tiempo.setText("")
        tiempo = os.path.join(resources_path, "images", "tiempo.png")
        self.tiempo.setPixmap(QtGui.QPixmap(tiempo))
        self.tiempo.setScaledContents(True)
        self.tiempo.setObjectName("tiempo")
        self.horizontalLayout_2.addWidget(self.tiempo)
        self.engranaje = QtWidgets.QLabel(Form)
        self.engranaje.setMinimumSize(QtCore.QSize(0, 1))
        self.engranaje.setMaximumSize(QtCore.QSize(45, 45))
        self.engranaje.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.engranaje.setText("")
        engranaje = os.path.join(resources_path, "images", "engranaje.png")
        self.engranaje.setPixmap(QtGui.QPixmap(engranaje))
        self.engranaje.setScaledContents(True)
        self.engranaje.setObjectName("engranaje")
        self.horizontalLayout_2.addWidget(self.engranaje)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 1)
        self.horizontalLayout_2.setStretch(7, 1)
        self.horizontalLayout_2.setStretch(8, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setMinimumSize(QtCore.QSize(500, 0))
        self.tableView.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 5, 15, -1)
        self.verticalLayout.setSpacing(28)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add_nomina = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_nomina.setFont(font)
        self.btn_add_nomina.setObjectName("btn_add_nomina")
        self.verticalLayout.addWidget(self.btn_add_nomina)
        self.crear_empleado_gestion = QtWidgets.QPushButton(Form)
        self.crear_empleado_gestion.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.crear_empleado_gestion.setFont(font)
        self.crear_empleado_gestion.setStyleSheet("")
        self.crear_empleado_gestion.setObjectName("crear_empleado_gestion")
        self.verticalLayout.addWidget(self.crear_empleado_gestion)
        self.eliminar_empleado_gestion = QtWidgets.QPushButton(Form)
        self.eliminar_empleado_gestion.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.eliminar_empleado_gestion.setFont(font)
        self.eliminar_empleado_gestion.setStyleSheet("")
        self.eliminar_empleado_gestion.setObjectName("eliminar_empleado_gestion")
        self.verticalLayout.addWidget(self.eliminar_empleado_gestion)
        self.editar_empleado_gestion = QtWidgets.QPushButton(Form)
        self.editar_empleado_gestion.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Sinhala ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.editar_empleado_gestion.setFont(font)
        self.editar_empleado_gestion.setStyleSheet("")
        self.editar_empleado_gestion.setObjectName("editar_empleado_gestion")
        self.verticalLayout.addWidget(self.editar_empleado_gestion)
        self.btn_search_nomina = QtWidgets.QComboBox(Form)
        self.btn_search_nomina.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search_nomina.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_search_nomina.setAutoFillBackground(False)
        self.btn_search_nomina.setStyleSheet("QComboBox {\n"
"    qproperty-alignment: \'AlignCenter\'; /* Centrar texto visible */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    text-align: center; /* Centrar texto en opciones desplegables */\n"
"}\n"
"")
        self.btn_search_nomina.setEditable(False)
        self.btn_search_nomina.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.btn_search_nomina.setPlaceholderText("")
        self.btn_search_nomina.setDuplicatesEnabled(False)
        self.btn_search_nomina.setFrame(True)
        self.btn_search_nomina.setObjectName("btn_search_nomina")
        self.btn_search_nomina.addItem("")
        self.btn_search_nomina.setItemText(0, "Busqueda de Personal")
        self.btn_search_nomina.addItem("")
        self.btn_search_nomina.addItem("")
        self.btn_search_nomina.addItem("")
        self.btn_search_nomina.addItem("")
        self.btn_search_nomina.addItem("")
        self.btn_search_nomina.addItem("")
        self.btn_search_nomina.addItem("")
        self.verticalLayout.addWidget(self.btn_search_nomina)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(10, 200))
        self.label.setMaximumSize(QtCore.QSize(800, 800))
        self.label.setStyleSheet("")
        self.label.setText("")
        userOnDesktop = os.path.join(resources_path, "images", "userOnDesktop.png")
        self.label.setPixmap(QtGui.QPixmap(userOnDesktop))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.personal_tab.setText(_translate("Form", "Gestor de Personal"))
        self.nomina_semanal_tab.setText(_translate("Form", "Gestor de Nominas\n"
"Semanal"))
        self.nomina_quincenal_tab.setText(_translate("Form", "Gestor de Nominas\n"
"Quincenal"))
        self.nomina_mensual_tab.setText(_translate("Form", "Gestor de Nominas\n"
"Mensual"))
        self.cestatickets_tab.setText(_translate("Form", "Gestor de Nominas\n"
"Cestatickets"))
        self.all_nominas.setText(_translate("Form", "Todas las Nominas"))
        self.btn_add_nomina.setText(_translate("Form", "Añadir Nuevo Empleado"))
        self.crear_empleado_gestion.setText(_translate("Form", "Crear Empleado de Gestion"))
        self.eliminar_empleado_gestion.setText(_translate("Form", "Eliminar Empleado de Gestion"))
        self.editar_empleado_gestion.setText(_translate("Form", "Editar Empleado de Gestion"))
        self.btn_search_nomina.setCurrentText(_translate("Form", "Busqueda de Personal"))
        self.btn_search_nomina.setItemText(1, _translate("Form", "Alfabeticamente A-Z"))
        self.btn_search_nomina.setItemText(2, _translate("Form", "Alfabeticamente Z-A"))
        self.btn_search_nomina.setItemText(3, _translate("Form", "Cedula (mayor a menor)"))
        self.btn_search_nomina.setItemText(4, _translate("Form", "Cedula (menor a mayor)"))
        self.btn_search_nomina.setItemText(5, _translate("Form", "Por Cedula"))
        self.btn_search_nomina.setItemText(6, _translate("Form", "Por Nombre"))
        self.btn_search_nomina.setItemText(7, _translate("Form", "Por Apellido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
